export const SET_CONTACTS_VIEW = 'SET_CONTACTS_VIEW';
export const FETCH_USERS = 'FETCH_USERS';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

